# Generated by Django 4.1.3 on 2023-01-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='date_of_manufacture',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='model',
        ),
    ]
