# Generated by Django 4.1.3 on 2023-01-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0002_remove_brand_date_of_manufacture_remove_brand_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('exact_price', models.IntegerField()),
                ('date_of_upload', models.DateField()),
                ('description', models.TextField(max_length=1500)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_site.brand')),
                ('category', models.ManyToManyField(to='test_site.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
