# Generated by Django 4.1.3 on 2023-01-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0004_medicalequipment_productinstance_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalequipment',
            old_name='price',
            new_name='price_in_euros',
        ),
    ]
