# Generated by Django 4.1.3 on 2023-01-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0005_rename_price_medicalequipment_price_in_euros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinstance',
            old_name='device',
            new_name='medicalequipment',
        ),
    ]
